### ISSUE TITLE
fails to build on system with sha2 v0.10 and v0.11

### ISSUE THREAD

**Issue by jonassmedegaard** [oxigraph/oxigraph#1712]
On a Debian system with both v0.10 and v0.11 available, build fails like this:

```
error[E0277]: the trait bound `sha2::Sha256: md5::Digest` is not satisfied
    --> lib/spareval/src/expression.rs:1146:70
     |
1146 |             Function::Sha256 => build_hash_expression_evaluator::<_, Sha256>(parameters, context)?,
     |                                                                      ^^^^^^ the trait `md5::digest::FixedOutput` is not implemented for `sha2::Sha256`
     |
note: there are multiple different versions of crate `digest` in the dependency graph
    --> /build/oxigraph-0.5.8+ds/debian/cargo_registry/digest-0.10.7/src/lib.rs:93:1
     |
  93 | pub trait FixedOutput: Update + OutputSizeUser + Sized {
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ this is the expected trait
     |
    ::: /build/oxigraph-0.5.8+ds/debian/cargo_registry/digest-0.11.3/src/lib.rs:95:1
     |
  95 | pub trait FixedOutput: Update + OutputSizeUser + Sized {
     | ------------------------------------------------------ this is the found trait
     = help: you can use `cargo tree` to explore your dependency tree
help: the trait `md5::digest::FixedOutput` is implemented for `CoreWrapper<T>`
    --> /build/oxigraph-0.5.8+ds/debian/cargo_registry/digest-0.10.7/src/core_api/wrapper.rs:163:1
     |
 163 | / impl<T> FixedOutput for CoreWrapper<T>
 164 | | where
 165 | |     T: FixedOutputCore,
 166 | |     T::BlockSize: IsLess<U256>,
 167 | |     Le<T::BlockSize, U256>: NonZero,
     | |____________________________________^
     = note: required for `sha2::Sha256` to implement `md5::Digest`
note: required by a bound in `build_hash_expression_evaluator`
    --> lib/spareval/src/expression.rs:1662:78
     |
1662 | fn build_hash_expression_evaluator<'a, C: ExpressionEvaluatorContext<'a>, H: Digest>(
     |                                                                              ^^^^^^ required by this bound in `build_hash_expression_evaluator`

error[E0277]: the trait bound `sha2::Sha256: md5::Digest` is not satisfied
    --> lib/spareval/src/expression.rs:1146:70
     |
1146 |             Function::Sha256 => build_hash_expression_evaluator::<_, Sha256>(parameters, context)?,
     |                                                                      ^^^^^^ the trait `md5::digest::HashMarker` is not implemented for `sha2::Sha256`
     |
note: there are multiple different versions of crate `digest` in the dependency graph
    --> /build/oxigraph-0.5.8+ds/debian/cargo_registry/digest-0.10.7/src/digest.rs:8:1
     |
   8 | pub trait HashMarker {}
     | ^^^^^^^^^^^^^^^^^^^^ this is the expected trait
     |
    ::: /build/oxigraph-0.5.8+ds/debian/cargo_registry/digest-0.11.3/src/digest.rs:10:1
     |
  10 | pub trait HashMarker {}
     | -------------------- this is the found trait
     = help: you can use `cargo tree` to explore your dependency tree
     = help: the following other types implement trait `md5::digest::HashMarker`:
               CoreWrapper<T>
               CtVariableCoreWrapper<T, OutSize, O>
               Md5Core
               RtVariableCoreWrapper<T>
               Sha1Core
     = note: required for `sha2::Sha256` to implement `md5::Digest`
note: required by a bound in `build_hash_expression_evaluator`
    --> lib/spareval/src/expression.rs:1662:78
     |
1662 | fn build_hash_expression_evaluator<'a, C: ExpressionEvaluatorContext<'a>, H: Digest>(
     |                                                                              ^^^^^^ required by this bound in `build_hash_expression_evaluator`

error[E0277]: the trait bound `sha2::Sha384: md5::Digest` is not satisfied
    --> lib/spareval/src/expression.rs:1147:70
     |
1147 |             Function::Sha384 => build_hash_expression_evaluator::<_, Sha384>(parameters, context)?,
     |                                                                      ^^^^^^ the trait `md5::digest::FixedOutput` is not implemented for `sha2::Sha384`
     |
note: there are multiple different versions of crate `digest` in the dependency graph
    --> /build/oxigraph-0.5.8+ds/debian/cargo_registry/digest-0.10.7/src/lib.rs:93:1
     |
  93 | pub trait FixedOutput: Update + OutputSizeUser + Sized {
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ this is the expected trait
     |
    ::: /build/oxigraph-0.5.8+ds/debian/cargo_registry/digest-0.11.3/src/lib.rs:95:1
     |
  95 | pub trait FixedOutput: Update + OutputSizeUser + Sized {
     | ------------------------------------------------------ this is the found trait
     = help: you can use `cargo tree` to explore your dependency tree
help: the trait `md5::digest::FixedOutput` is implemented for `CoreWrapper<T>`
    --> /build/oxigraph-0.5.8+ds/debian/cargo_registry/digest-0.10.7/src/core_api/wrapper.rs:163:1
     |
 163 | / impl<T> FixedOutput for CoreWrapper<T>
 164 | | where
 165 | |     T: FixedOutputCore,
 166 | |     T::BlockSize: IsLess<U256>,
 167 | |     Le<T::BlockSize, U256>: NonZero,
     | |____________________________________^
     = note: required for `sha2::Sha384` to implement `md5::Digest`
note: required by a bound in `build_hash_expression_evaluator`
    --> lib/spareval/src/expression.rs:1662:78
     |
1662 | fn build_hash_expression_evaluator<'a, C: ExpressionEvaluatorContext<'a>, H: Digest>(
     |                                                                              ^^^^^^ required by this bound in `build_hash_expression_evaluator`

error[E0277]: the trait bound `sha2::Sha384: md5::Digest` is not satisfied
    --> lib/spareval/src/expression.rs:1147:70
     |
1147 |             Function::Sha384 => build_hash_expression_evaluator::<_, Sha384>(parameters, context)?,
     |                                                                      ^^^^^^ the trait `md5::digest::HashMarker` is not implemented for `sha2::Sha384`
     |
note: there are multiple different versions of crate `digest` in the dependency graph
    --> /build/oxigraph-0.5.8+ds/debian/cargo_registry/digest-0.10.7/src/digest.rs:8:1
     |
   8 | pub trait HashMarker {}
     | ^^^^^^^^^^^^^^^^^^^^ this is the expected trait
     |
    ::: /build/oxigraph-0.5.8+ds/debian/cargo_registry/digest-0.11.3/src/digest.rs:10:1
     |
  10 | pub trait HashMarker {}
     | -------------------- this is the found trait
     = help: you can use `cargo tree` to explore your dependency tree
     = help: the following other types implement trait `md5::digest::HashMarker`:
               CoreWrapper<T>
               CtVariableCoreWrapper<T, OutSize, O>
               Md5Core
               RtVariableCoreWrapper<T>
               Sha1Core
     = note: required for `sha2::Sha384` to implement `md5::Digest`
note: required by a bound in `build_hash_expression_evaluator`
    --> lib/spareval/src/expression.rs:1662:78
     |
1662 | fn build_hash_expression_evaluator<'a, C: ExpressionEvaluatorContext<'a>, H: Digest>(
     |                                                                              ^^^^^^ required by this bound in `build_hash_expression_evaluator`

error[E0277]: the trait bound `sha2::Sha512: md5::Digest` is not satisfied
    --> lib/spareval/src/expression.rs:1148:70
     |
1148 |             Function::Sha512 => build_hash_expression_evaluator::<_, Sha512>(parameters, context)?,
     |                                                                      ^^^^^^ the trait `md5::digest::FixedOutput` is not implemented for `sha2::Sha512`
     |
note: there are multiple different versions of crate `digest` in the dependency graph
    --> /build/oxigraph-0.5.8+ds/debian/cargo_registry/digest-0.10.7/src/lib.rs:93:1
     |
  93 | pub trait FixedOutput: Update + OutputSizeUser + Sized {
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ this is the expected trait
     |
    ::: /build/oxigraph-0.5.8+ds/debian/cargo_registry/digest-0.11.3/src/lib.rs:95:1
     |
  95 | pub trait FixedOutput: Update + OutputSizeUser + Sized {
     | ------------------------------------------------------ this is the found trait
     = help: you can use `cargo tree` to explore your dependency tree
help: the trait `md5::digest::FixedOutput` is implemented for `CoreWrapper<T>`
    --> /build/oxigraph-0.5.8+ds/debian/cargo_registry/digest-0.10.7/src/core_api/wrapper.rs:163:1
     |
 163 | / impl<T> FixedOutput for CoreWrapper<T>
 164 | | where
 165 | |     T: FixedOutputCore,
 166 | |     T::BlockSize: IsLess<U256>,
 167 | |     Le<T::BlockSize, U256>: NonZero,
     | |____________________________________^
     = note: required for `sha2::Sha512` to implement `md5::Digest`
note: required by a bound in `build_hash_expression_evaluator`
    --> lib/spareval/src/expression.rs:1662:78
     |
1662 | fn build_hash_expression_evaluator<'a, C: ExpressionEvaluatorContext<'a>, H: Digest>(
     |                                                                              ^^^^^^ required by this bound in `build_hash_expression_evaluator`

error[E0277]: the trait bound `sha2::Sha512: md5::Digest` is not satisfied
    --> lib/spareval/src/expression.rs:1148:70
     |
1148 |             Function::Sha512 => build_hash_expression_evaluator::<_, Sha512>(parameters, context)?,
     |                                                                      ^^^^^^ the trait `md5::digest::HashMarker` is not implemented for `sha2::Sha512`
     |
note: there are multiple different versions of crate `digest` in the dependency graph
    --> /build/oxigraph-0.5.8+ds/debian/cargo_registry/digest-0.10.7/src/digest.rs:8:1
     |
   8 | pub trait HashMarker {}
     | ^^^^^^^^^^^^^^^^^^^^ this is the expected trait
     |
    ::: /build/oxigraph-0.5.8+ds/debian/cargo_registry/digest-0.11.3/src/digest.rs:10:1
     |
  10 | pub trait HashMarker {}
     | -------------------- this is the found trait
     = help: you can use `cargo tree` to explore your dependency tree
     = help: the following other types implement trait `md5::digest::HashMarker`:
               CoreWrapper<T>
               CtVariableCoreWrapper<T, OutSize, O>
               Md5Core
               RtVariableCoreWrapper<T>
               Sha1Core
     = note: required for `sha2::Sha512` to implement `md5::Digest`
note: required by a bound in `build_hash_expression_evaluator`
    --> lib/spareval/src/expression.rs:1662:78
     |
1662 | fn build_hash_expression_evaluator<'a, C: ExpressionEvaluatorContext<'a>, H: Digest>(
     |                                                                              ^^^^^^ required by this bound in `build_hash_expression_evaluator`
```

Oxigraph permits v0.10 - v0.12 of sha2. This is unusually generous, and I appreciate declaring as relaxed as possible dependencies: Flexibility in dependencies is a great aid for downstream maintenance! That said, perhaps it is too relaxed in this case?

Patching to require at least v0.11 of sha2 results in same build failure.

Patching to require only v0.10 of sha2 makes the build succeed.

Debian generally strives to maintain only a single version of each crate, but recently introduced a branched sha2, so that (likely only for a limited time, but in Debian time is counted in months and years, not weeks) both v0.10 and v0.11 is available concurrently.

NB! There is a risk of Debian-specific patches causing this breakage, so please be suspicious and consider testing if reproducible before diving in too far.
